### ISSUE TITLE
`%cd` magic does not work

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#11]
Is this the pending PR request will address, or can be fixed without upstream changes?

![2018-05-08-11-44-30_scrot](https://user-images.githubusercontent.com/917985/39770710-667dfdfe-52b5-11e8-958c-e982307272c6.png)

**Comment by BoPeng** [comment]
`%cd` does not change the current directory of a running kernel so it need to be executed before the kernel is started.

I could not find a way to change current directory of a running process.

**Comment by BoPeng** [comment]
But when I think of this problem now, I think we can define a command for each kernel and execute it silently to change directory with the `%cd` magic.

**Comment by gaow** [comment]
So this is indeed specific to JupyterLab and related to the PR? Because back in SoS notebook:

![2018-05-08-12-08-10_scrot](https://user-images.githubusercontent.com/917985/39771667-969a7776-52b8-11e8-9ef6-e9e2f215d743.png)

and I've been relying on this feature to keep my notebook out of the dir with messy output data files.

**Comment by BoPeng** [comment]
No. If you start a subkernel before you use `%cd`, `%cd` does not apply to the subkernel. 

This should be the same for JLab and Jupyter Notebook.

**Comment by BoPeng** [comment]
* `sos`: `os.chdir(os.path.expanduser(to_dir))`
* `python2`/`python3`: the same
* `R`: `setwd(dir)`
* `matlab`: `cd dir` 
* `node`/`javascript`: `process.chdir('/tmp');`
* `bash`: `cd dir`
* `SAS`: `x 'cd <full path>';` (according to [here](https://stackoverflow.com/questions/6222093/change-current-folder))
* `julia`: `cd("/")`

A potential problem is that `dir` might be given in a format that is not acceptable to some of the kernels.

**Comment by BoPeng** [comment]
From Jupyter Notebook, not lab

1. `cd` before kernel starts

![image](https://user-images.githubusercontent.com/9889312/39772174-20245736-52ba-11e8-940c-4fc0536023e3.png)

2. `cd` after kernel starts

![image](https://user-images.githubusercontent.com/9889312/39772149-0a8e5336-52ba-11e8-826b-85ea638c6684.png)

**Comment by BoPeng** [comment]
Fixed.

![image](https://user-images.githubusercontent.com/9889312/39779388-a6cb0dde-52ce-11e8-9f4c-4d2edf239f53.png)
