### ISSUE TITLE
Magic does not work after error

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#16]
I've got various issues in my recent experiences with JupyterLab that I did not get a chance to report until today. But let me start with maybe only a couple of them hoping that they are somewhat related and the fix of one leads to fix of another. Here is the first one:

![2018-06-11-11-18-08_scrot](https://user-images.githubusercontent.com/917985/41244000-65f26bee-6d69-11e8-84cb-69744a2a65c4.png)

To reproduce, open up SoS and use an R cell to make a mistake. Then try some magic eg `%cd`. It will complain. 

Next, click on the reload icon to restart notebook:

![2018-06-11-11-24-52_scrot](https://user-images.githubusercontent.com/917985/41244239-135dd8fe-6d6a-11e8-87c3-87785f9f197a.png)

then the `cd` works, but will throw in a warning message:

![2018-06-11-11-25-30_scrot](https://user-images.githubusercontent.com/917985/41244277-2cf6066a-6d6a-11e8-9db4-e84ba2c08686.png)

**Comment by gaow** [comment]
I believe a similar yet slightly different symptom is observed for `%revisions` so I hope fixing this ticket will fix both.

**Comment by BoPeng** [comment]
The `%cd` R problem is caused by outdated `sos-r` module. Please upgrade.

**Comment by gaow** [comment]
Hmm seems so ... I'll leave the ticket open for a while until I confirm my other unreported ill-behaved magics work after the upgrade. Thanks a lot!

**Comment by gaow** [comment]
Okay in my ticket I reported 2 things:

1. `cd_command` issue after error, which is fixed after upgrade.
2. click on the restart icon after error, and see the restart jupyter server prompt. That is not fixed by the upgrade.

**Comment by BoPeng** [comment]
I can somehow reproduce this bug by evaluate any cell, restart, and re-evaluate, if it is ok, restart kernel again.

**Comment by BoPeng** [comment]
The problem seems to have disappeared. I have added a few debug messages for kernel change so please re-open this ticket with message copied from the browser console window if you still experience any problem with missing sos-comm.
