### ISSUE TITLE
Comment format issue before content

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#17]
See screenshot below: appearance of comment before section are not consistent.

![2018-06-16-08-02-03_scrot](https://user-images.githubusercontent.com/917985/41498812-bb62f078-713b-11e8-8659-676ae101fe15.png)

**Comment by BoPeng** [comment]
Jupyter lab only? Which source file it is?

**Comment by gaow** [comment]
It is the `RNASeqDE.ipynb` you are playing with now. 

Actually the Notebook version is worse:

![2018-06-16-09-12-37_scrot](https://user-images.githubusercontent.com/917985/41499411-806d567a-7145-11e8-8386-116b24c57f24.png)

**Comment by BoPeng** [comment]
I see, the `download` action uses markdown formatting and contaminated the rest of the cell.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/41499552-8d606a5a-7147-11e8-9976-235a7c1eb2d5.png)

Did you run `python -m sos_notebook.install` after installation?

**Comment by BoPeng** [comment]
The comment before `[hg19_reference_...]` is still considered a HTML header and is still wrong. This is because of the change of comment style and have to be addressed though.
