### ISSUE TITLE
Sticky kernel for new cells.

### ISSUE THREAD

**Issue by BoPeng** [vatlab/jupyterlab-sos#18]
Moved from vatlab/sos-notebook#95

I'm testing this in the jupyterlab-sos extension, and the behavior is correctly sticky.

However, one of the UI changes may create additional confusion, namely, the removal of the cell-level kernel menu.

Current behavior:

Create a notebook using SoS kernel
Set R kernel in first cell dropdown kernel menu, execute x=3
In next cell execute x
Call fails because default kernel is SoS
Change default kernel to R
In next cell execute x
Call succeeds
Change default kernel to F#
In next cell execute let y = 2
In next cell execute y
Calls succeed
Problem: UI no longer shows kernel type of previously executed cells

Possible solution: keep dropdown kernel menu for each cell

![sos](https://user-images.githubusercontent.com/4432084/42044240-1736097c-7abe-11e8-84e9-b71bba80e433.png)

**Comment by gaow** [comment]
Yes I can confirm it. And another thing is when I restart my notebook in the Lab I lost my previous setting. All revert back to SoS -- not sure if that can be reproduced.

**Comment by BoPeng** [comment]
So you guys are actually using JLab now? I do not like using JLab without `%preview` and C-S-Enter so I have not used it actively. The line-by-line execution PR will be merged soon though.

**Comment by gaow** [comment]
%preview works for me in the main notebook. I'm mostly on the Lab these days except when I need features it does not have #14. There are glitches here and there but some were difficult to reproduce and report ...

**Comment by BoPeng** [comment]
The side panel is a much more complex issue and a much bigger change to be pushed upstream, because it involves a new messaging type and related mechanism. I think it makes sense to rely on the console window for everything for now and make jupyterlab-sos work.

They finally decided to accept my line by line execution PR (not the shortcut though) after some resistance, which is a big relief for me.

**Comment by aolney** [comment]
Tested in Chrome, looks great :+1:

**Comment by BoPeng** [comment]
Great! I will pay more attention to this extension since more people are switching to JupyterLab. With the line-by-line execution PR being merged to JLab beta3, this extension should be more or less usable compared to SoS for classic Jupyter.
