### ISSUE TITLE
f-string syntax highlight looks bad on Dark theme JupyterLab

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#23]
Thought this might provide some eye protection, but ..: 

![2018-08-22-11-50-48_scrot](https://user-images.githubusercontent.com/917985/44477936-be23de80-a601-11e8-9bd0-ae49e2d94ba2.png)

**Comment by BoPeng** [comment]
How does searches text show there?

**Comment by gaow** [comment]
shows up fine:

![2018-08-22-12-07-42_scrot](https://user-images.githubusercontent.com/917985/44478682-03e1a680-a604-11e8-9960-18eca0ab53f4.png)

**Comment by BoPeng** [comment]
I am fine with the `f-string` part and it was actually my contribution to syntax highlight expressions inside f-string. I am more concerned with our own highlighting and you basically need to play in inspection mode and find the right css and change [here](https://github.com/vatlab/jupyterlab-sos/blob/master/style/index.css#L9). I am at IAH and cannot really work on this now.

**Comment by gaow** [comment]
I think transparency matters so instead of changing the color I changed it to:

```
	 background-color: rgb(237, 213, 243, 0.3);
```

unfortunately it does not work. Need to get back to my task for now. Will revisit.
