### ISSUE TITLE
Preview hint words not visible on dark theme

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#24]
Perhaps not urgent, but similar to #23 the dark theme for preview looks bad:

![2018-09-04-18-31-01_scrot](https://user-images.githubusercontent.com/917985/45062938-eb947180-b070-11e8-8547-5ab8300e99c8.png)

which should in fact look like:

![2018-09-04-18-31-19_scrot](https://user-images.githubusercontent.com/917985/45062941-f2bb7f80-b070-11e8-8d4e-729f03fecc4b.png)

that is the message prompts are not visible in dark theme.

**Comment by BoPeng** [comment]
![image](https://user-images.githubusercontent.com/9889312/51506313-660c2680-1db1-11e9-9f70-4527bffead28.png)
