### ISSUE TITLE
Kernel dropdown list broken in cells

### ISSUE THREAD

**Issue by thompsonmj** [vatlab/jupyterlab-sos#26]
When creating a new file in Jupyter Lab, I can select a kernel for the file (SoS), but selecting a kernel for a cell in the file does not work. That is, the drop down flashes quickly when clicked and disappears before I can select a kernel.

**Comment by BoPeng** [comment]
Are you using the latest JupyterLab and JupyterLab-sos? On which is?

**Comment by BoPeng** [comment]
Just tested on mac, with latest version of jupyterlab (0.34.11) and jupyterlab-sos (0.2.4) and everything seems to be ok.

![image](https://user-images.githubusercontent.com/9889312/45771287-549bed80-bc0a-11e8-9cbf-9c1b01d3e5d5.png)

![image](https://user-images.githubusercontent.com/9889312/45771361-87de7c80-bc0a-11e8-9392-d78ffa47b495.png)

**Comment by thompsonmj** [comment]
OK, I just tried in a different browser, and it is working fine. There seems to be an issue with Firefox, but Chrome works well. Also using jl 0.34.11 and jl-sos 0.2.4 on macOS.

**Comment by BoPeng** [comment]
OK, I just downloaded firefox and can confirm the problem you had. Checking what is happening now.

**Comment by BoPeng** [comment]
Please confirm if jupyterlab-sos 0.2.5 has fixed this issue.

**Comment by thompsonmj** [comment]
Great! Works like a charm now.
