### ISSUE TITLE
JupyterLab 1.0.0

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#35]
Since JupyterLab 1.0.0 has just been released I want to upgrade to use the release. Before I proceed:

1. Do we have a list of features available in SoS Notebook but not JupyterLab, due to your pending PR out there? Ideally would be nice to see them in README.md
2. Is the current release + dependency packages the most up to date and I can install via instructions: https://github.com/vatlab/jupyterlab-sos#installation ?
3. What happened to the `toc` feature, do we have an alternative?

Thanks!

**Comment by BoPeng** [comment]
1, 2, yes, even `README.md` is up to date. For 3, see [here](https://github.com/vatlab/jupyterlab-sos/issues/25#issuecomment-501350030).
