### ISSUE TITLE
Line by line execution does not work after restart kernel

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#37]
To reproduce below:

1. create a new notebook and type in the first 2 lines in the cell as screen shot below shows
2. run them line by line
3. restart the kernel by clicking on the semi-circled arrow in the tool bar
4. run them line by line again we get communication error

However, creatting a new notebook will work as expected so there is apparently no need to restart the server. 

<img width="552" alt="Screen Shot 2019-07-02 at 10 07 01 AM" src="https://user-images.githubusercontent.com/917985/60524057-7c4bd600-9cb1-11e9-82d9-73808ca47493.png">

**Comment by BoPeng** [comment]
Pushed a new version (0.4.7), let me know if it fixes the problem, and if there is any side effect.

**Comment by gaow** [comment]
No still no luck. It seems simply restart the kernel via the circle arrow icon will nto work:

![2019-07-03-09-34-33_scrot](https://user-images.githubusercontent.com/917985/60600532-efb71b80-9d75-11e9-8e60-a26825b5de5c.png)

Is it the case on your end too? @BoPeng? Also `%preview` is broken for me:

![2019-07-03-09-34-53_scrot](https://user-images.githubusercontent.com/917985/60600581-03fb1880-9d76-11e9-9c4b-b888ded047d5.png)

I updated to Jupyter Lab 1.0.0 a couple of days ago. I am on jupyter-sos 0.4.7.

**Comment by BoPeng** [comment]
Line by line execution is messed up here, perhaps because of changes in sos and sos notebook. I am checking what is going on.

**Comment by BoPeng** [comment]
It is actually an unrelated bug, I have fixed it and released 0.4.8. The kernel-restart problem is fixed according to what I can see here.

**Comment by BoPeng** [comment]
Step through `input` and `output`

![image](https://user-images.githubusercontent.com/9889312/60625792-71c33680-9dae-11e9-9fc8-ec350ab18ea1.png)

Step through `a=4`, `b=5`, restart and re-step through

![image](https://user-images.githubusercontent.com/9889312/60625831-8d2e4180-9dae-11e9-9d05-d87f5d7102b2.png)
