### ISSUE TITLE
%preview magic broken

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#38]
`%preview` for PNG/PDF files do not work for the latest release.

**Comment by BoPeng** [comment]
Here are what I observed

1. `%preview -n a1.png` works. Figure display in notebook.
2. `%preview a1.png` with `C-S-Enter` works. Figure display in console panel.
3. `%preview a1.png` with console panel open works. Figure display in console panel.
4. `%preview a1.png` without console panel does not work.

Is 4 the case that you are complaining? Generally speaking `%preview a1.png` should send output to console but in this case console is not open. As far as I remember, `%preview a1.png` in classic jupyter shows the figure in the notebook, right?

**Comment by gaow** [comment]
> Is 4 the case that you are complaining?

Yes sorry I should have clarified that -- I used `%preview -n`. I always use it without the console, in order to save the preview to my main notebook. 

> As far as I remember, %preview a1.png in classic jupyter shows the figure in the notebook, right?

That's what I too recall.

**Comment by BoPeng** [comment]
Fixed and released jupyterlab-sos 0.4.9.
