### ISSUE TITLE
Code folding behavior

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#50]
I noticed in current version for an SoS cell even one line of code in it, when I close and reopen the codes get hidden:

![image](https://user-images.githubusercontent.com/917985/76530543-3c490f80-644a-11ea-9c60-9a09486b6208.png)

which scares me for a second until I click on it then it shows up. 

The 2nd cell above is just a one line of `%cd` command.

It seems something can be improved though not sure if it is easy enough. eg always show two lines in that folded cell with one line the first line of the hidden code and another line to prompt that it can be expanded.

**Comment by BoPeng** [comment]
I think jupyterlab-sos does not do any folding. Could you try to see if you have the same problem with a Python kernel?

**Comment by gaow** [comment]
Hmm somehow i'm not able to reproduce the behavior now even with SoS kernel ... I've left in some python codes there and see what happens next time. R cells seem fine, no automatic folding, at least in this one notebook am working on.
