### ISSUE TITLE
Syntax highlight problem

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#51]
I remember previously `${_input}` etc would be highlighted with solid pinkish background color. The highlight is now gone using JupyterLab 2.0.1 and current version of jupyterlab-sos. 

![image](https://user-images.githubusercontent.com/917985/76801684-831d6900-67ac-11ea-971f-fd6953193ead.png)

The workflow file is [here](https://github.com/gaow/SEQLinkage/blob/master/data/genemap/genemap.ipynb)

**Comment by BoPeng** [comment]
Yes, I noticed it as well but have not got a chance to look at it. It should be an easy fix.

**Comment by BoPeng** [comment]
It works here

![image](https://user-images.githubusercontent.com/9889312/79034398-35153e80-7b7b-11ea-8474-4d4892e0abd8.png)


![image](https://user-images.githubusercontent.com/9889312/79034414-4f4f1c80-7b7b-11ea-870a-03e94fca2104.png)

With the latest JLab and Jupyterlab-sos. Could you double-check?
