### ISSUE TITLE
Drop menu added to console of notebook in other kernels

### ISSUE THREAD

**Issue by BoPeng** [vatlab/jupyterlab-sos#55]
This is console for a Python3 notebook, but a dropdown menu is added.

<img width="979" alt="Screen Shot 2020-06-05 at 9 18 50 AM" src="https://user-images.githubusercontent.com/9889312/83887115-9ab22100-a70d-11ea-99cb-45c69f3c7de7.png">

**Comment by nibheis** [comment]
Hi @BoPeng !
Thanks for your hard work on jupyterlab-sos.
I just noticed that the drop down menu also appears all code cells, for any type of kernel (Python, R, Bash, C, etc.) with JupyterLab 3.x.
We are using jupyterlab-sos 0.8.7
Can I configure this behavior somewhere, or is it a bug ?

**Comment by BoPeng** [comment]
Let me have a look.

**Comment by BoPeng** [comment]
I have fixed the issue and released jupyterlab-sos v0.8.8.

It puzzled me for a while when jupyterlab-sos did not work after the update. It turns out that it is a [known issue with firefox](https://github.com/jupyter/notebook/issues/2396), switching to chrome solved the problem.

**Comment by nibheis** [comment]
Trying it right now... and it works. Perfect! Thanks a lot!
