### ISSUE TITLE
Update for JLab 3.0

### ISSUE THREAD

**Issue by BoPeng** [vatlab/jupyterlab-sos#57]
https://github.com/jupyterlab/jupyterlab/issues/8038

We should prepare for the release of JLab 3.0.

**Comment by gaow** [comment]
JupyterLab 3.0 is out already and I already get complaints about incompatibility. I have not verified it myself, but would it be good enough to bump the required version check to include JLab 3.0 and fix it?

**Comment by BoPeng** [comment]
Thanks for the reminder. Hopefully the api change was minimal.

**Comment by BoPeng** [comment]
Updated. It is good that extensions can now be installed through `pip install`.

**Comment by gaow** [comment]
@BoPeng I verified that the installation works with a fresh miniconda install, but I see the last commit in this repo was still from months ago. Perhaps you forgot to push? 


>  It is good that extensions can now be installed through pip install.

Should we update our installation instruction then?

**Comment by BoPeng** [comment]
Thanks. Will have a look.

**Comment by BoPeng** [comment]
Thanks, just pushed and updated README. Working on vatlab/sos#1424 now.
