### ISSUE TITLE
kernel dropdown menu overlapped with the cell toolbar

### ISSUE THREAD

**Issue by whyjz** [vatlab/jupyterlab-sos#60]
Hello jupyterlab-sos developers -- 

Jupyterlab 3.3 introduces the cell toolbar, which occupies the place the kernel dropdown menu spawns:
![jupyter-sos-issue](https://user-images.githubusercontent.com/19339926/178124494-0b372d09-19e3-4ca3-9cfc-aff5dd5a8ff5.png)

**Comment by BoPeng** [comment]
yes, I am aware of that but have not got around to find a solution. Ideally, it there is an existing toolbar, we should try to insert our dropdown to it...

**Comment by whyjz** [comment]
Maybe there's a way to change the CSS so that the dropdown always shows to the left of the toolbar buttons? 

Each toolbar button can be enabled or disabled in the JupyterLab settings, and all the enabled buttons always stack from the right. So I think there might be a way to use the same technique for the dropdown.

**Comment by BoPeng** [comment]
#61 made some progress but the dropdown disappears after leaving and re-selecting the cell. There must be some "hook" to use to add the dropdown to the toolbar each time.

**Comment by BoPeng** [comment]
https://jupyterlab.readthedocs.io/en/stable/extension/extension_points.html?highlight=cell%20toolbar#toolbar-registry documents how to add new items to the toolbar.

**Comment by BoPeng** [comment]
@whyjz 

Finally get it working with help from the Jupyterlab developers! Please update to jupyterlab-sos 0.8.7 and let me know if there is any remaining problem.
