### ISSUE TITLE
Switching to non-SoS kernel does not hide the language dropdown

### ISSUE THREAD

**Issue by BoPeng** [vatlab/jupyterlab-sos#74]
@choran reported this from #72 

How to reproduce
1. Start a sos notebook
2. Change kernel to R
3. The language dropdown stays.
4. Insert a new cell, the language dropdown is still created.

Even if it is difficult to remove dropdown menu from existing cell toolbars, new cells should not have them.

**Comment by Ichoran** [comment]
I can confirm that this solves the issue for me: new cells don't get the dropdown, and old ones fix themselves once you switch between cells.  (In both directions: SoS to non-SoS removes the menu, while non-SoS to SoS adds it back.)
