### ISSUE TITLE
Testing out basic features

### ISSUE THREAD

**Issue by gaow** [vatlab/jupyterlab-sos#9]
I just tried it out for some basic features. Actually it seems to work for basic user case like I listed above, and the `%toc` came back after installing the `jupyterlab-toc` extension. See my notebook attached.

[test.ipynb.zip](https://github.com/vatlab/sos-notebook/files/1977082/test.ipynb.zip)

However there are 2 glitches not sure if it is related to upstream PR:

1. When I start a new SoS notebook from Jupyter lab there is no cell-level language drop-down selector menu. But if I open one from existing Jupyter Notebook version, then I get the menu as in my attached notebook, and I was able to use it to switch between kernels. Why doesn't it show up by default?

2. Running every cell manually sequentially works well. But when I click on "Restart and run all" there comes an error message:

![2018-05-05-15-53-30_scrot](https://user-images.githubusercontent.com/917985/39667461-7f19011e-507c-11e8-804f-aff0089a5078.png)

Even though it still seems to be working:

![2018-05-05-15-55-08_scrot](https://user-images.githubusercontent.com/917985/39667472-c0f7478a-507c-11e8-816e-bf8b034497fd.png)

3. It feels a bit slow, presumably because many things do not work and drags it slow.

Otherwise as a code editor and non-communicating multi-language doodle pad, it seems to be good enough to actually use, if 1 & 2 are addressed.

**Comment by BoPeng** [comment]
1 should be fixed. You will have to run `.build.sh` to install it.

**Comment by gaow** [comment]
Great! 

> You will have to run .build.sh to install it.

Previously I followed installation instruction on `README.md`. I noticed `build.sh` is slightly different from the README instruction (the last line seem to differ). Would you kindly take a look and recommend on README the most suitable sequence of commands to run?

**Comment by BoPeng** [comment]
The README was provided by a jupyterlab template for extensions. I do not know the `link` command. I suppose both commands would work?

**Comment by gaow** [comment]
Okay sounds like install is the way to go. `link` is like linking to the current directory, but `install` actually puts the extension to somewhere else in the system?

**Comment by BoPeng** [comment]
Install installs to JupyterLab and link should be linking to current directory so you do not have to install again after the extension changes.

**Comment by BoPeng** [comment]
2 should be fixed.

**Comment by gaow** [comment]
I can confirm the fix. Though the only minor complaint is that it takes quite long time to run `build.sh`

**Comment by BoPeng** [comment]
OK. I have published jupyterlab 0.1.1 so do not have to compile from source (at least for next time).

So with these fixes the sos kernel itself more or less works with JupyterLab, and the only missing ones are all the frontend features (side panel, line by line execution), and the magics that depends on these features (preview etc). I suppose these have to wait for the upstream PRs.
